# Generated by Django 4.0.2 on 2022-02-16 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_is_author_alter_blogitem_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogitem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.category'),
        ),
    ]
