# Generated by Django 4.0.2 on 2022-02-16 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_user_is_author_alter_blogitem_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogitem',
            name='likes',
            field=models.ManyToManyField(related_name='blog_item', to=settings.AUTH_USER_MODEL),
        ),
    ]
