# Generated by Django 4.0.2 on 2022-02-16 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_blogitem_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogitem',
            name='dislikes',
            field=models.ManyToManyField(related_name='blog_item_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogitem',
            name='likes',
            field=models.ManyToManyField(related_name='blog_item_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
