# Generated by Django 4.0.2 on 2022-02-19 04:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_comment_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogitem',
            name='views',
            field=models.ManyToManyField(related_name='blog_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
