# Generated by Django 4.0.2 on 2022-02-19 08:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_blogitem_views_alter_comment_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogitem',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
