# Generated by Django 4.0.2 on 2022-02-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_user_address_user_age_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='workplace',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
